# Generated by Django 3.2.9 on 2021-11-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
