# Generated by Django 3.2.9 on 2021-11-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsa_app', '0002_remove_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsachecklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='jsachecklist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='JSAChecklist',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
