# Generated by Django 3.2.9 on 2021-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsa_app', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
